# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./../flagStonePort/transform-util-cxx/transform-util
# Target is a library:  
QT       += core gui xml svg

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QMAKE_CFLAGS += -w -fpermissive
QMAKE_CXXFLAGS += -w -fpermissive -std=c++11

INCLUDEPATH += ../../transform-cxx-bsd \
               .
# Keep the archive path relative. MinGW ar -M splits an absolute path that contains spaces.
DESTDIR = libout
CONFIG += release warn_off staticlib c++11
CONFIG -= debug warn_on 
TEMPLATE = lib 
HEADERS += FSCodec.h \
           FSImageConstructor.h \
           FSShapeConstructor.h \
           FSSoundConstructor.h \
           FSTextConstructor.h \
           FSTransformUtil.h \
           transformutil.h 
SOURCES += FSCodec.cpp \
           FSImageConstructor.cpp \
           FSShapeConstructor.cpp \
           FSSoundConstructor.cpp \
           FSTextConstructor.cpp \
           FSTransformUtil.cpp 
